### ISSUE TITLE
Extend readme to show basic integration with hadoop / spark etc.. add luigi resources

### ISSUE THREAD

**Issue by Analect** [Jay-Oh-eN/data-engineering-101#3]
@Jay-Oh-eN 
Thanks for your session last night.
Was wondering if you could add the slides to the repo ... and also if it might be possible to extend the readme to provide some guidelines around getting this pipeline working with a more complex set-up and not just local files.
If you could share links to some of the other useful luigi resources you have been able to find, that would be much appreciated.
Thanks.

**Comment by Jay-Oh-eN** [comment]
added a presentation to the repository as well as uploaded it to Slideshare [here](http://www.slideshare.net/jonathandinu/presentation-45784222)

There is an example for using luigi with Hadoop in `hadoop_word_count.py` and a good presentation on Luigi in general is in the readme but also will link to it here: [http://www.slideshare.net/erikbern/luigi-presentation-nyc-data-science](http://www.slideshare.net/erikbern/luigi-presentation-nyc-data-science)

Let me know if you want any more resources or guidance!
